// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"math/rand"
)

func chooseRandomHeadline() string {
	headlines := []string{
		"Quick Chews for Busy Shoes",
		"Eat Lazy, Live Easy",
		"Easy Eats, Lazy Feasts",
		"Bite Easy, Live Lazy",
		"Quick Bites for Busy Nights",
		"Speedy Eats for Busy Bees",
		"Just Click, Cook Quick",
	}

	return headlines[rand.Intn(len(headlines))]
}

func Navigation(isAuthenticated bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"border-b py-3\"><div class=\"container mx-auto flex justify-between items-center\"><!-- Left side: Lazy Meal logo and Meal Guide (on desktop) --><div class=\"flex items-center gap-6\"><!-- Logo --><div class=\"text-lg text-foreground\"><a href=\"/\" class=\"font-semibold uppercase\">🍲 lazy<span class=\"text-green-600\">meal</span></a></div><!-- Meal Guide Button (only next to logo on desktop) --><a href=\"/meal-guide\" class=\"hidden md:block bg-green-600 text-white px-4 py-2 rounded-lg shadow hover:bg-green-700 transition text-sm font-semibold\">Get your Meal Guide</a></div><!-- Right side on desktop: Random headline and Auth button --><div class=\"flex gap-4 items-center text-sm\"><!-- Random headline (only on desktop) --><div class=\"hidden md:block\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(chooseRandomHeadline())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/components/navigation.templ`, Line: 39, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "!</div><!-- create meal button -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isAuthenticated {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<button class=\"bg-green-100 text-green-500 w-8 h-8 flex items-center justify-center rounded-md hover:bg-green-200 hover:text-green-600 transition transform active:scale-90 shadow-sm\"><a href=\"/create\"><i class=\"fas fa-add text-sm\"></i></a></button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><!-- Meal Guide Button on mobile (rightmost on mobile) --><a href=\"/meal-guide\" class=\"block md:hidden bg-green-600 text-white px-4 py-2 rounded-lg shadow hover:bg-green-700 transition text-sm font-semibold\">Get your Meal Guide</a></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
