// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "lazymeal/app/views/layouts"

func PrivacyPolicyIndex(isAuthenticated bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"py-12\"><h1 class=\"text-4xl font-bold mb-6\">Privacy Policy</h1><p class=\"mb-4\">Lazy Meal does not collect personal data directly. However, we use third-party services like Plausible Analytics for tracking site performance and Google Ads for displaying advertisements. These services may collect non-personally identifiable information such as browser type, device, and interaction with the website.</p><h2 class=\"text-2xl font-semibold mt-6 mb-4\">Cookies and Tracking</h2><p class=\"mb-4\">We do not use cookies for tracking directly. Plausible Analytics is a privacy-focused tool that does not use cookies or collect personal data. Google Ads may use cookies to personalize ads. You can manage cookies through your browser settings.</p><h2 class=\"text-2xl font-semibold mt-6 mb-4\">Third-Party Services</h2><h2 class=\"text-2xl font-semibold mt-6 mb-4\">Your Rights</h2><p class=\"mb-4\">Google Ads may display personalized ads based on your browsing behavior. Please review Google's for more details. <a href=\"https://policies.google.com/technologies/ads\" class=\"text-blue-500\">Ads Privacy Policy</a></p><p class=\"mb-4\">If you are located in the EU, you have the right to opt-out of data tracking and request the deletion of your data. You can disable ads personalization through Google settings.</p><h2 class=\"text-2xl font-semibold mt-6 mb-4\">Contact Us</h2><p>If you have any questions about this Privacy Policy, please contact us at <a href=\"mailto:contact.tripod557@passinbox.com\" class=\"text-blue-500\">contact.tripod557@passinbox.com</a>.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.App(isAuthenticated, "Privacy Policy", "").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
