// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meal_guide_whitelist.sql

package sqlc

import (
	"context"
)

const getWaitlistCount = `-- name: GetWaitlistCount :one
SELECT COUNT(*) FROM meal_guide_whitelists
`

func (q *Queries) GetWaitlistCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWaitlistCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEmail = `-- name: InsertEmail :one
INSERT INTO meal_guide_whitelists (email,discount) VALUES (?1, ?2)
RETURNING id, email, discount, created_at
`

type InsertEmailParams struct {
	Email    string
	Discount float64
}

func (q *Queries) InsertEmail(ctx context.Context, arg InsertEmailParams) (MealGuideWhitelist, error) {
	row := q.db.QueryRowContext(ctx, insertEmail, arg.Email, arg.Discount)
	var i MealGuideWhitelist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Discount,
		&i.CreatedAt,
	)
	return i, err
}
