// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meals.sql

package sqlc

import (
	"context"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (
    name, category, description, short_description,
    image_url, image_preview, calories, likes, total_effort,
    instruction_steps, cook_time, prep_time, total_time, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10,
    ?11, ?12, ?13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, name, category, description, short_description, image_url, image_preview, calories, likes, total_effort, instruction_steps, cook_time, prep_time, total_time, created_at, updated_at
`

type CreateMealParams struct {
	Name             string
	Category         string
	Description      string
	ShortDescription string
	ImageUrl         string
	ImagePreview     string
	Calories         int64
	Likes            int64
	TotalEffort      int64
	InstructionSteps string
	CookTime         int64
	PrepTime         int64
	TotalTime        int64
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.ShortDescription,
		arg.ImageUrl,
		arg.ImagePreview,
		arg.Calories,
		arg.Likes,
		arg.TotalEffort,
		arg.InstructionSteps,
		arg.CookTime,
		arg.PrepTime,
		arg.TotalTime,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.ShortDescription,
		&i.ImageUrl,
		&i.ImagePreview,
		&i.Calories,
		&i.Likes,
		&i.TotalEffort,
		&i.InstructionSteps,
		&i.CookTime,
		&i.PrepTime,
		&i.TotalTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllMeals = `-- name: GetAllMeals :many
SELECT id, name, category, description, short_description, image_url, image_preview, calories, likes, total_effort, instruction_steps, cook_time, prep_time, total_time, created_at, updated_at FROM meals
`

func (q *Queries) GetAllMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.ShortDescription,
			&i.ImageUrl,
			&i.ImagePreview,
			&i.Calories,
			&i.Likes,
			&i.TotalEffort,
			&i.InstructionSteps,
			&i.CookTime,
			&i.PrepTime,
			&i.TotalTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMealsPaginated = `-- name: GetAllMealsPaginated :many


SELECT id, name, category, description, short_description, image_url, image_preview, calories, likes, total_effort, instruction_steps, cook_time, prep_time, total_time, created_at, updated_at FROM meals
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type GetAllMealsPaginatedParams struct {
	Limit  int64
	Offset int64
}

// SELECT * FROM meals
// WHERE created_at > ?1
// ORDER BY created_at DESC
// LIMIT ?2;
func (q *Queries) GetAllMealsPaginated(ctx context.Context, arg GetAllMealsPaginatedParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, getAllMealsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.ShortDescription,
			&i.ImageUrl,
			&i.ImagePreview,
			&i.Calories,
			&i.Likes,
			&i.TotalEffort,
			&i.InstructionSteps,
			&i.CookTime,
			&i.PrepTime,
			&i.TotalTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
