// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Meal struct {
	ID                       int64
	Name                     string
	Category                 string
	Servings                 int64
	Description              string
	LightVersionInstructions sql.NullString
	Instructions             string
	ImageUrl                 string
	Calories                 int64
	Protein                  int64
	CookTime                 int64
	PrepTime                 int64
	TotalTime                int64
	WashingEffort            int64
	PeelingEffort            int64
	CuttingEffort            int64
	ItemsRequired            string
	Ingredients              string
	TotalEffort              int64
	Likes                    int64
	CreatedAt                time.Time
	UpdatedAt                time.Time
	ImageAlt                 sql.NullString
}

type Session struct {
	ID        int64
	Token     interface{}
	UserID    int64
	IpAddress sql.NullString
	UserAgent sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID              int64
	Email           string
	PasswordHash    string
	FirstName       string
	LastName        string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}
