// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	Author    string
	Content   string
	Approved  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	MealID    int64
}

type CookItem struct {
	ID            int64
	Name          string
	WashingEffort int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MealID        int64
}

type Ingredient struct {
	ID            int64
	Name          string
	Unit          string
	Amount        int64
	Calories      int64
	WashingEffort int64
	CuttingEffort int64
	PellingEffort int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MealID        int64
}

type Meal struct {
	ID               int64
	Name             string
	Category         string
	Description      string
	ShortDescription string
	ImageUrl         string
	ImagePreview     string
	Calories         int64
	Likes            int64
	TotalEffort      int64
	InstructionSteps string
	CookTime         int64
	PrepTime         int64
	TotalTime        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Nutrition struct {
	ID           int64
	Name         string
	Unit         string
	Amount       int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IngredientID int64
}

type Session struct {
	ID        int64
	Token     interface{}
	UserID    int64
	IpAddress sql.NullString
	UserAgent sql.NullString
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID              int64
	Email           string
	PasswordHash    string
	FirstName       string
	LastName        string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}
